# Generated by Django 4.1 on 2023-08-24 11:58

import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='Username', error_messages={'unique': 'A user with this username already exists.'}, help_text='Required. 31 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=15, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()])),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('count', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.user')),
            ],
        ),
    ]
